### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by alexaky260** [SebLavK/BearMyBanner#10]
I know how to use mods. I have allot and use Vortex. But I can't get this mod to work. I tested it in custom battle because I've lost all my saves xD

**Comment by SebLavK** [comment]
Custom battles don't have banners loaded yet because units are loaded in a different way. I'm working on it at the moment. Try setting the ratio to 1 and allow all tiers, you'll see everybody using a banner in the campaign. Then tweak it to your liking!
