### ISSUE TITLE
Check is Mission.CombatType == Tournament

### ISSUE THREAD

**Issue by brandonm4** [SebLavK/BearMyBanner#2]
Getting an error assigning banners in tournaments - you can check the combat type of the mission for Combat, TOurnament or None and only assign banners when appropriate.
 if (Mission.Current.CombatType == Mission.MissionCombatType.Combat)

Also, just curious - why are you using OnApplicationTick to check for the mission instead of the OnMissionInit event?

Other than that, seems like a really neat mod.

**Comment by SebLavK** [comment]
Using OnApplicationTick was a quick and easy way of getting to the point where I could play with the agents equipment. Basically, to test things out and get the mod working.

Finding a better hook is what I'm going to tackle tomorrow. I've tried `OnMissionBehaviourInitialize` but agents haven't been initialized by then (I found one of the behaviours includes equipment assignment while perusing through the native DLLs).

I haven't seen `OnMissionInit` yet. Is it overriden from `MBSubModuleBase` or something else? I just got into coding for Bannerlord this week, and this is my first true project with C#, I'm learning its differences with Java.

**Comment by brandonm4** [comment]
OnMissionBehaviourInitialize is what I meant I just didn't have it in front of me :)
Not sure this will work - but if you make your behavior class inherit from MissionLogic you can use AfterStart() from inside the behavior - Agents may be initialized by then.   So instead of directly altering the agents - create a behavior, during the OnMissionBehaviorInitialize, check to see if this is a proper mission for you to alter, and if so, add your behavior to the mission.  Inside that behavior, when agents are initialized, adjust the banners. (Maybe, theoretically)

**Comment by SebLavK** [comment]
Great tip! Yes, I also remember seeing `AfterStart` while decompiling the native files, but I had just started and didn't understand the architecture very well. Definitely starting with that tomorrow.

What error are you getting when assigning banners in tournaments? Agents not having an Origin perhaps? (Of the top of my head).

I do plan on getting banners into tournaments, checking

**Comment by brandonm4** [comment]
It's not giving me the exact error - just that when the tournament starts there's a message in the lower left that says something along the lines of error assigning banners.  It doesn't crash, tournament plays out fine.

**Comment by SebLavK** [comment]
Just changed the mod so it uses behaviours like you suggested, I can't thank you enough for that!

`AfterStart` didn't have the agents initialized by then, but I can use `OnFormationUnitsSpawned`, which triggers when each side spawns its troops (only the first wave, unfortunately, so I might need to use one of the Agent spawn methods and change some of the logic for assigning banners).

Also, there's no `MissionCombatType.Tournament` that I've seen, but with these last changes Tournaments don't trigger the assignment logic, and so no more errors.

Regarding the swapping of weapons on the fly... It's tricky. There's a handy method called `EquipWeaponToExtraSlotAndWield` that I use to give a banner.
I haven't found a way to directly access the `Equipment` list for an agent. Instead, I clone the `SpawnEquipment` without weapons (is an option, though ammunition doesn't count as a weapon), add the new weapons I want and `UpdateSpawnEquipmentAndRefreshVisuals`.
This last bit seems like having a weapon equipped and the mesh (visual) attached to the character's hand or holster are two different things.
You can check out how I use all that to remove ranged weapons from agents here: [](https://github.com/SebLavK/BearMyBanner/blob/master/BearMyBanner/BattleBannerAssignBehaviour.cs#L118)
I'll open a thread in the modding forums to talk about that, if there isn't one already.
